version: "3.8"

services:
  tensorflow_jupyter:
    container_name: tensorflow_jupyter
    image: tensorflow-cert-gpu
    build: ./
    ports:
      - ${PORT}:8888
    volumes:
      - ./:/home/${USERNAME}/app
    command: jupyter lab --ip 0.0.0.0 --NotebookApp.token='' --NotebookApp.password=''
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
