version: '3.8'
services:
  tensorflow_cert_jupyter:
    container_name: tensorflow_cert_jupyter
    image: tensorflow-cert-gpu
    build: ./
    working_dir: /app
    ports:
      - ${port}:8888
    volumes:
      - ./config/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py
      - ./:/app
    command: jupyter notebook
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
